package:
    name: cryptopp
    version: 5.6.5
source:
    fn: CRYPTOPP-5_6_5.tar.gz
    patches: ''
    sha256: 79fd5514b3b191a1c6d934cd989d5e058f4726a72a3dad2444bd1274a6aae686
    url: https://github.com/weidai11/cryptopp/archive/CRYPTOPP_5_6_5.tar.gz
build:
    noarch: ''
    noarch_python: false
    number: '0'
    string: '0'
    skip: true    # [py<36]
    features:     # [win and py36]
        - vc14    # [win and py36]
requirements:
    build:
        - cmake
        - toolchain
        - gcc-7           # [linux and not armv7l]
    run:
        - vs2015_runtime  # [win]
        - libgcc-7        # [linux and not armv7l]
test:
    commands:
        - if exist %LIBRARY_LIB%\cryptopp-static.lib (exit 0) else (exit 1)                          # [win]
        - if exist %LIBRARY_LIB%\cmake\cryptopp\cryptopp-config.cmake (exit 0) else (exit 1)         # [win]
        - if exist %LIBRARY_LIB%\cmake\cryptopp\cryptopp-config-version.cmake (exit 0) else (exit 1) # [win]
        - test -f $PREFIX/lib/libcryptopp.a                                                          # [unix]
        - test -f $PREFIX/lib/cmake/cryptopp/cryptopp-config.cmake                                   # [unix]
        - test -f $PREFIX/lib/cmake/cryptopp/cryptopp-config-version.cmake                           # [unix]
about:
    home: https://www.cryptopp.com
    license: Boost-1.0
    license_file: License.txt
    summary: A C++ Class Library of Cryptographic Schemes
extra:
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - JohanMabille
        - gouarin
