language: generic
os: osx
osx_image: xcode6.4
env:
  matrix:
  - CONDA_PY=36
  global:
  - secure: shgVS6ohLYWfEw9ByKSl8lObV1prpvn+hXuEXas9zTZfkNHolCTeRj6z4AvckYyyYfOpO0TCDUP5hvIU2Lv9M2QwuTRsYG7auogr6HEuQW1ll4nOSpLDdf9i69bmkrc2+KKbwgnFCiUAxVj3q0RXTnvJBxbfyBkL0mb8JpWYxnKzIq8RjzBts3oF+Tx2YNdiAlWUJi1QY9ZPA3mBuCdKEne+6H9szZUpOQDfRu37Ak4YRgxeQ0Dajvn50q6TdVIDmgCrAtNSecXawrkWntiaxIYJCVrydq55aGo64QWDq4/31aEIW71RIeNz7xznQIBf3ZRvSY7b3TuwaiKFbr1fSl3qnAA9JKzqVMRjBB8iYZf0XMDyc7UMNtU9WjJYpDTGUx36wU6hbdzn9d8RIbv4doyyKFzKqFqL4Nilq2pM5TFI4ASl4h3m2wi+aYOu4mcMlhQheECXs/HFUFiac5y4YGzX/cYrg26PC7qBhBgR7PTx0NQHFnB2l9tH3S3MTVlk5Y9H0Q5wpviXVjixW0TkRFGq/VSZyBEB0uoNyksIY7q9QXnVVYeRA54NjjL5BsCMeZqcI8PSEw6vSx9eAdDncHC0yZodBX+6AkMdzBklWaIkQOQA8gw6wrI8vAPa0wDp8J/ZykB7+Yf3mwxT4XzAgVG4aLk2KFuzwrEBz38bFzo=
before_install:
- |
  (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
      python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
- |
  echo ""
  echo "Removing homebrew from Travis CI to avoid conflicts."
  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
  chmod +x ~/uninstall_homebrew
  ~/uninstall_homebrew -fq
  rm ~/uninstall_homebrew
install:
- |
  echo ""
  echo "Installing a fresh version of Miniconda."
  MINICONDA_URL="https://repo.continuum.io/miniconda"
  MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
  curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
  bash $MINICONDA_FILE -b
- |
  echo ""
  echo "Configuring conda."
  source /Users/travis/miniconda3/bin/activate root
  conda config --remove channels defaults
  conda config --add channels defaults
  conda config --add channels conda-forge
  conda config --add channels QuantStack
  conda config --set show_channel_urls true
  conda install --yes --quiet conda-forge-build-setup
  source run_conda_forge_build_setup
script:
- conda build ./recipe
- upload_or_check_non_existence ./recipe QuantStack --channel=main
